### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by VandaLHJ** [thebracket/noxfutura#3]
On cargo build:

error[E0308]: mismatched types
  --> nox_planet/src/region/builder/debris.rs:32:20
   |
32 |             if let Some(entry) = ecs.entry_ref(*e) {
   |                    ^^^^^^^^^^^   ----------------- this expression has type `std::result::Result<EntryRef<'_>, EntityAccessError>`
   |                    |
   |                    expected enum `std::result::Result`, found enum `std::option::Option`
   |
   = note: expected enum `std::result::Result<EntryRef<'_>, EntityAccessError>`
              found enum `std::option::Option<_>`
On stable-x86_64-unknown-linux-gnu unchanged - rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by thebracket** [comment]
Huh, Github picked up the close and didn't link to the issue properly. Basically, I was linking to an older Legion (not updated), and they cleaned up entries being an Option and components from an entry being a Result. Makes more sense for both to be results. The linked commit fixes the dependencies and uses the newer syntax.
